#!/usr/bin/env python3
"""Generate js/scans.js: per-province original-scan PDF maps + tavola labels.

Scans downloads/sources/{year}/provinces/*.pdf (filenames {COD3}_{Name}_{year}.pdf)
and writes a shared JS file used by index.qmd and test/population.qmd.
"""

import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
YEARS = [1861, 1871, 1881, 1901, 1911, 1921, 1931, 1936]

# tavola originale per censimento (cf. docs/fonti_tavole_province.md)
TAVOLE = {
    1861: "TAVOLA II", 1871: "Tavola II", 1881: "TAVOLA II",
    1901: "TAV. XX", 1911: "TAVOLA IV", 1921: "TAVOLA XIV",
    1931: "TAVOLA IX", 1936: "TAVOLA X",
}


def main() -> None:
    lines = ["// generated by scripts/build_scans_js.py — do not edit by hand",
             "// per-province original census scans (L. Lionello's selections)"]
    lines.append("const SCAN_TAVOLE = {"
                 + ", ".join(f"{y}: '{t}'" for y, t in TAVOLE.items()) + "};")
    lines.append("const SCANS = {")
    for year in YEARS:
        d = ROOT / "downloads" / "sources" / str(year) / "provinces"
        if not d.is_dir():
            print(f"WARNING: {d} missing, year skipped")
            continue
        entries = []
        for pdf in sorted(d.glob("*.pdf")):
            m = re.match(r"(\d{3})_", pdf.name)
            if not m:
                print(f"WARNING: unparsable filename {pdf.name}")
                continue
            # NFC to match git/GitHub Pages; escape \ and ' for JS literal
            name = unicodedata.normalize("NFC", pdf.name)
            name = name.replace("\\", "\\\\").replace("'", "\\'")
            entries.append(f"{int(m.group(1))}:'{name}'")
        lines.append(f"  {year}: {{{', '.join(entries)}}},")
        print(f"{year}: {len(entries)} scans")
    lines.append("};")

    out = ROOT / "js" / "scans.js"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"-> {out}")


if __name__ == "__main__":
    main()
